# core/crypter.py
# Шифрование/расшифровка payload для BlindSpot.

import os
import struct


def xor_encrypt(data: bytes, key: bytes) -> bytes:
    """XOR-шифрование с многобайтным ключом (повторяется по длине)."""
    if not key:
        raise ValueError("Key cannot be empty")
    out = bytearray(len(data))
    klen = len(key)
    for i, b in enumerate(data):
        out[i] = b ^ key[i % klen]
    return bytes(out)


def xor_decrypt(data: bytes, key: bytes) -> bytes:
    """XOR-расшифровка (то же самое, что и шифрование)."""
    return xor_encrypt(data, key)


def rc4_crypt(data: bytes, key: bytes) -> bytes:
    """RC4 — симметричный потоковый шифр."""
    S = list(range(256))
    j = 0
    klen = len(key)
    for i in range(256):
        j = (j + S[i] + key[i % klen]) & 0xFF
        S[i], S[j] = S[j], S[i]

    out = bytearray(len(data))
    i = j = 0
    for n, b in enumerate(data):
        i = (i + 1) & 0xFF
        j = (j + S[i]) & 0xFF
        S[i], S[j] = S[j], S[i]
        k = S[(S[i] + S[j]) & 0xFF]
        out[n] = b ^ k
    return bytes(out)


def generate_key(length: int = 16) -> bytes:
    """Случайный ключ."""
    return os.urandom(length)


def encrypt(data: bytes, algorithm: str = "xor") -> tuple:
    """
    Возвращает (ciphertext, key).
    algorithm: "xor" или "rc4".
    """
    if algorithm == "xor":
        key = generate_key(16)
        return xor_encrypt(data, key), key
    elif algorithm == "rc4":
        key = generate_key(16)
        return rc4_crypt(data, key), key
    else:
        raise ValueError(f"Unknown algorithm: {algorithm}")


def decrypt(data: bytes, key: bytes, algorithm: str = "xor") -> bytes:
    if algorithm == "xor":
        return xor_decrypt(data, key)
    elif algorithm == "rc4":
        return rc4_crypt(data, key)
    else:
        raise ValueError(f"Unknown algorithm: {algorithm}")


def to_c_array(data: bytes, name: str = "g_payload", per_line: int = 16) -> str:
    """Формирует C-код массива из bytes."""
    lines = []
    lines.append(f"// Auto-generated by core/crypter.py — do not edit")
    lines.append(f"const unsigned char {name}[] = {{")
    for i in range(0, len(data), per_line):
        chunk = data[i:i+per_line]
        hex_bytes = ", ".join(f"0x{b:02X}" for b in chunk)
        lines.append(f"    {hex_bytes},")
    lines.append("};")
    lines.append(f"const unsigned int {name}_size = {len(data)};")
    return "\n".join(lines) + "\n"